### ISSUE TITLE
Can't install any package

### ISSUE THREAD

**Issue by jesseaial5** [cirebon-dev/replit_kalilinux#1]
Hi
I have an issue. Whenever I want to install a package using "apt" I encounter with an error, for example when I want to install Python3 using:

>> apt-get install python3 -y

I get this error:

```
Creating user 'systemd-network' (systemd Network Management) with UID 998 and GID 998.
Failed to rename /etc/.#groupccbb6 to /etc/group: Invalid cross-device link

dpkg: error processing package systemd (--configure):

 installed systemd package post-installation script subprocess returned error exit status 1

Setting up libncursesw6:amd64 (6.4+20231016-1) ...

Setting up readline-common (8.2-1.3) ...

Setting up libtirpc3:amd64 (1.3.3+ds-1) ...

Setting up libreadline8:amd64 (8.2-1.3) ...

Setting up libnsl2:amd64 (1.3.0-2) ...

Setting up libpython3.11-stdlib:amd64 (3.11.6-3) ...

Setting up libpython3-stdlib:amd64 (3.11.4-5+b1) ...

Setting up python3.11 (3.11.6-3) ...

Setting up python3 (3.11.4-5+b1) ...

running python rtupdate hooks for python3.11...

running python post-rtupdate hooks for python3.11...

Processing triggers for libc-bin (2.37-12) ...

Errors were encountered while processing:

 systemd

E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Can you address this issue?

**Comment by guangrei** [comment]
> Hi I have an issue. Whenever I want to install a package using "apt" I encounter with an error, for example when I want to install Python3 using:
> 
> > > apt-get install python3 -y
> 
> I get this error:
> 
> ```
> Creating user 'systemd-network' (systemd Network Management) with UID 998 and GID 998.
> Failed to rename /etc/.#groupccbb6 to /etc/group: Invalid cross-device link
> 
> dpkg: error processing package systemd (--configure):
> 
>  installed systemd package post-installation script subprocess returned error exit status 1
> 
> Setting up libncursesw6:amd64 (6.4+20231016-1) ...
> 
> Setting up readline-common (8.2-1.3) ...
> 
> Setting up libtirpc3:amd64 (1.3.3+ds-1) ...
> 
> Setting up libreadline8:amd64 (8.2-1.3) ...
> 
> Setting up libnsl2:amd64 (1.3.0-2) ...
> 
> Setting up libpython3.11-stdlib:amd64 (3.11.6-3) ...
> 
> Setting up libpython3-stdlib:amd64 (3.11.4-5+b1) ...
> 
> Setting up python3.11 (3.11.6-3) ...
> 
> Setting up python3 (3.11.4-5+b1) ...
> 
> running python rtupdate hooks for python3.11...
> 
> running python post-rtupdate hooks for python3.11...
> 
> Processing triggers for libc-bin (2.37-12) ...
> 
> Errors were encountered while processing:
> 
>  systemd
> 
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```
> 
> Can you address this issue?
Did you run apt update first?

i have test install python3 like you but has no problem (see screenshot)
![Screenshot_20231030-013212](https://github.com/cirebon-dev/replit_kalilinux/assets/20879950/2b87cb1e-3d7a-44cd-b59d-143d1b8d5385)

**Comment by jesseaial5** [comment]
Thanks for your quick reply.
And yes, first I ran "apt update" then "apt install curl -y" . These 2 commands executed successfully but after that whenever I want to install a package I face the above error.

**Comment by guangrei** [comment]
> Thanks for your quick reply. And yes, first I ran "apt update" then "apt install curl -y" . These 2 commands executed successfully but after that whenever I want to install a package I face the above error.
> 
> Can you test that If you can install another package after that?

this is my test install curl then install vim, everything works well
![2023-10-30_2-20-51](https://github.com/cirebon-dev/replit_kalilinux/assets/20879950/a30974b0-d3c9-4c4f-93ab-7028a98bfa10)

**Comment by jesseaial5** [comment]
I tried to install "vim" and I got this again:

![11](https://github.com/cirebon-dev/replit_kalilinux/assets/149326697/c8ae6043-d033-422c-b150-ab8cd7d403d7)

**Comment by guangrei** [comment]
Maybe after installing Curl you ran a script or program which caused you to not be able to install anything else
